// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Static page describing how to connect AI agents to the hosted MCP server, with a link to the Swagger UI.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Landing page",
                "responses": {
                    "200": {
                        "description": "HTML landing page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/app/launch/{system_id}/{app_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits an analysis. The body is optional; missing fields get defaults: a generated\nanalysis name, an output directory under the user's home, the email from the JWT,\ndebug=false, and notify=true. Swagger UI placeholder values are stripped.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "Launch an app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution system id (e.g. de)",
                        "name": "system_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "App UUID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "iRODS zone for the output directory (defaults to the configured zone)",
                        "name": "output_zone",
                        "in": "query"
                    },
                    {
                        "description": "Analysis submission; all fields optional",
                        "name": "submission",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.LaunchSubmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "analysis_id, name, status, plus url for VICE analyses",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid app ID or request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists apps with optional filters. Date filters use the form \u003coperator\u003e\u003cISO-8601 date\u003e,\ne.g. '\u003e2025-09-29' or '\u003c=2024-12-31T23:59:59' (see docs/DATE_FILTERING.md).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "List apps available to the user",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Page size (1-1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term forwarded to the apps service",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "vice",
                            "interactive",
                            "de",
                            "osg",
                            "tapis"
                        ],
                        "type": "string",
                        "description": "Job type filter",
                        "name": "job_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive substring match on the description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive substring match on the integrator username",
                        "name": "integrator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date filter on the integration date",
                        "name": "integration_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date filter on the last-edited date",
                        "name": "edited_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "total and apps",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid pagination value or date filter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/analyses/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists analyses filtered by status (default Running). Pass status with an empty value to list all analyses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "List the user's analyses",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Running",
                        "description": "Analysis status filter; explicitly empty lists all",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "analyses with analysis_id, name, app_id, system_id, and status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/analyses/{analysis_id}/control": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "extend_time extends the analysis's time limit; save_and_exit terminates it after saving outputs; exit terminates it without saving.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "Control a running VICE analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analysis UUID",
                        "name": "analysis_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "extend_time",
                            "save_and_exit",
                            "exit"
                        ],
                        "type": "string",
                        "description": "Operation to perform",
                        "name": "operation",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation result; includes the echoed operation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid operation or analysis ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/analyses/{analysis_id}/details": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "Get an analysis's full details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analysis UUID",
                        "name": "analysis_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The analysis record as returned by the apps service",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid analysis ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Apps service error (including unknown analyses)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/analyses/{analysis_id}/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analyses"
                ],
                "summary": "Get an analysis's status and VICE URL readiness",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Analysis UUID",
                        "name": "analysis_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "analysis_id, status, url_ready, plus url and url_check_details when a subdomain exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid analysis ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Apps service error (including unknown analyses)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/job-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "List supported job types",
                "responses": {
                    "200": {
                        "description": "job_types entries with name, description, and internal_name",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/apps/{system_id}/{app_id}/parameters": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apps"
                ],
                "summary": "Get an app's parameter groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution system id (e.g. de)",
                        "name": "system_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "App UUID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "groups and overall_job_type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid app ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Apps service error (including unknown apps)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/data/{path}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a JSON listing for collections, or streams raw file contents for data objects\n(offset/limit allow partial reads). With include_metadata=true, AVU metadata is returned\nin X-Datastore-{attribute} response headers, with value and units joined by avu_delimiter.",
                "produces": [
                    "application/json",
                    "application/octet-stream"
                ],
                "tags": [
                    "Data Store"
                ],
                "summary": "Browse a directory or download a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "iRODS path (e.g. cyverse/home/username)",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Starting byte offset when reading a file",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum bytes to read; 0 or absent reads to the end",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Include AVU metadata as response headers",
                        "name": "include_metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": ",",
                        "description": "Separator between value and units in metadata headers",
                        "name": "avu_delimiter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Directory listing (JSON) or raw file contents",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Access denied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Path not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send a request body to create or update a file; use resource_type=directory with no\nbody to create a collection; send no body to an existing path for a metadata-only\nupdate. Metadata is supplied via X-Datastore-{attribute} request headers (value and\nunits split on avu_delimiter). Swagger UI cannot send arbitrary headers; use curl for\nmetadata operations.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Store"
                ],
                "summary": "Upload a file, create a directory, or set metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "iRODS path",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "directory"
                        ],
                        "type": "string",
                        "description": "Set to directory to create a collection",
                        "name": "resource_type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Replace existing AVUs for the attributes being set instead of adding",
                        "name": "replace_metadata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": ",",
                        "description": "Separator between value and units in metadata headers",
                        "name": "avu_delimiter",
                        "in": "query"
                    },
                    {
                        "description": "Raw file content",
                        "name": "content",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "path, type, and created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Ambiguous operation or upload to a directory",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Access denied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Parent directory not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a data object or collection. Use dry_run=true to preview the outcome without\ndeleting. Deleting a non-empty directory requires recurse=true, in both real and\ndry-run mode.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data Store"
                ],
                "summary": "Delete a file or directory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "iRODS path",
                        "name": "path",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Allow deleting non-empty directories",
                        "name": "recurse",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Preview the deletion without executing it",
                        "name": "dry_run",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "path, type, would_delete, deleted, dry_run, and item_count for recursive non-empty directories",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Directory not empty",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Access denied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Path not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Exchanges HTTP Basic credentials for a Keycloak token using the password grant.\nUse the Authorize dialog's BasicAuth fields, run this endpoint, then paste the\naccess_token from the response into the BearerAuth field to call the other endpoints.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log in with username and password",
                "responses": {
                    "200": {
                        "description": "Keycloak token response (access_token, refresh_token, expires_in, ...)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Authentication service error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get the authenticated user's profile",
                "responses": {
                    "200": {
                        "description": "username, email, name, preferred_username",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid or missing token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.LaunchSubmission": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "debug": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notify": {
                    "type": "boolean"
                },
                "output_dir": {
                    "type": "string"
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "A Keycloak JWT prefixed with \"Bearer \". Obtain one via POST /login.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "formation",
	Description:      "REST API for the CyVerse Discovery Environment: app discovery and launching, analysis management, and iRODS data access.\n\nTo authenticate: open the Authorize dialog and enter your username and password under BasicAuth,\nrun POST /login, then copy the access_token from the response into the BearerAuth value\n(prefixed with \"Bearer \") to call the other endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
